id = "zed.vortx"
name = "vortx"
version = "0.1.0"
description = "Vortx workflow DSL syntax highlighting and language support"
authors = ["Mark Watts <mark@example.com>"]
repository = "https://github.com/mwatts/zed-vortx"
schema_version = 1

[grammars.vortx]
repository = "https://github.com/mwatts/tree-sitter-vortx"
rev = "3a7e60192f7221be04e861d7846e5bbe7a197f55"

[grammars.rhai_expr]
repository = "https://github.com/mwatts/tree-sitter-rhai-expr"
rev = "17ac7f0fe1b25e8259678897fef4acdb8d382ffc"
